---
title: "mapa-nidos"
output: html_document
date: "2023-04-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1) coordenadas estacas
2) shape perímetro
3) datos estaca total nidos
4) eso por año y tipo de nido (nidos totales y prop cueva)

estaca | coord_x | coord_y | nidos_tot | prop_mata | año
1
2
3
4


```{r}
library(tidyverse)

```

```{r cargar datos nidos}
datos_ord <- read_csv2("datos_ord.csv", col_types = cols(
  Sample.Label = col_factor(),
  tipo_nido = col_factor(c("mata","cueva"))
)  )

datos_ord_2 <- datos_ord %>% 
  filter(!is.na(tipo_nido)) %>% 
  group_by(Sample.Label,año, tipo_nido) %>% 
  summarise(
    cant = n()
  )

nid_estaca <- datos_ord_2 %>% 
  pivot_wider(names_from = tipo_nido, values_from = cant) %>% 
  mutate(mata = replace_na(mata, 0),
         cueva = replace_na(cueva, 0)) %>% 
  mutate(
    total = mata + cueva,
    prop_mata = mata/total,
    prop_cueva = cueva/total
  )

```

```{r cargar datos perimetro y coord}
library(sf)
library(tmap)
library(ggspatial)

perimetro <-st_read("shapes/perimetro final/perimetro_2016 final.shp")

estacas <- st_read("shapes/Estacas/estacas pinguinera.shp")

plot(estacas$geometry)
#est <- estacas$geometry
#est <- st_zm(st_read("shapes/Estacas/estacas pinguinera.shp"),drop = TRUE, what = "ZM")


estacas2 <- estacas %>% 
  mutate(
    Sample.Label = str_extract(Name,"\\d+")) 

coord <- estacas2 %>% 
  st_coordinates() %>% 
  as.data.frame()

coord$Sample.Label <- estacas2$Sample.Label

# agregar recordatorio explicación regex
```

```{r mapas}

nid_estaca_coord <- nid_estaca %>% left_join(coord)
nid_estaca_coord <- st_as_sf(nid_estaca_coord, coords=c("X","Y"), crs= 4326)

plot(nid_estaca_coord)

#nidos de estacas por año
nid_estaca_coord %>% filter(año == "2015") %>% 
ggplot(data = .)+
  geom_sf(aes(size = total))+
  theme_light()

nid_estaca_coord %>% filter(año == "2016") %>% 
ggplot(data = .)+
  geom_sf(aes(size = total))+
  theme_light()

nid_estaca_coord %>% filter(año == "2017") %>% 
ggplot(data = .)+
  geom_sf(aes(size = total))+
  theme_light()

nid_estaca_coord %>% filter(año == "2018") %>% 
ggplot(data = .)+
  geom_sf(aes(size = total))+
  theme_light()

nid_estaca_coord %>% filter(año == "2019") %>% 
ggplot(data = .)+
  geom_sf(aes(size = total))+
  theme_light()

nid_estaca_coord %>% filter(año == "2021") %>% 
ggplot(data = .)+
  geom_sf(aes(size = total))+
  theme_light()

#mapa abundancia con ggplot
ping_plot <- nid_estaca_coord %>%
  ggplot() +
  geom_sf(data=perimetro, color="grey",alpha=0.6)+
  geom_sf(aes(size = total), col="lightblue")+
  geom_sf_text(data = nid_estaca_coord, 
               aes(label = Sample.Label),check_overlap = F, size=3,color = "black")+
  theme_light()+ 
  facet_wrap(~año)+
  labs(y = "Latitude", x = "Longitude", title = "Active nests per stake") +
  annotation_scale(location = "br", width_hint = 0.3,  
                   pad_x = unit(1, "cm"), pad_y = unit(0.5, "cm"))+
  annotation_north_arrow( location = "tl", pad_x = unit(0.2, "in"), pad_y = unit(0.1, "in"),
    style = north_arrow_fancy_orienteering)+
  theme(axis.text.x=element_text(size = 10), axis.text.y=element_text(size = 10), 
         axis.title.x = element_text(size=12, face="bold"), axis.title.y = element_text(size=12,face = "bold"),
        legend.title=element_text(size=12), legend.text = element_text(size=10))
ping_plot

ggsave("pinguinera.png",ping_plot,width = 30,
       height = 30,units = "cm" ,dpi = 600, ) #png

#mapa ambiente (cueva/mata)
#mata
mata_plot <- nid_estaca_coord %>%
  ggplot() +
  geom_sf(data=perimetro, color="grey",alpha=0.8)+
  geom_sf(aes(size = prop_mata), col="lightgreen")+
  geom_sf_text(data = nid_estaca_coord, 
               aes(label = Sample.Label),check_overlap = F, size=3,color = "black")+
  theme_light()+
  facet_wrap(~año)+
  labs(y = "latitude", x = "longitude", title = "Ratio of bush nests per stake") +
  theme_bw()+ 
  annotation_scale(location = "br", width_hint = 0.3,  
                   pad_x = unit(1, "cm"), pad_y = unit(0.5, "cm"))+
  annotation_north_arrow( location = "tl", pad_x = unit(0.2, "in"), pad_y = unit(0.1, "in"),
    style = north_arrow_fancy_orienteering)
mata_plot

ggsave("prop_mata.png",mata_plot,width = 30,
       height = 30,units = "cm" ,dpi = 500, ) #png

#cueva
cueva_plot <- nid_estaca_coord %>%
  ggplot() +
  geom_sf(data=perimetro, color="grey",alpha=0.8)+
  geom_sf(aes(size = prop_cueva), col="orange")+
  geom_sf_text(data = nid_estaca_coord, 
               aes(label = Sample.Label),check_overlap = F, size=3,color = "black")+
  theme_light()+
  facet_wrap(~año)+
  labs(y = "latitude", x = "longitude", title = "Ratio of burrows per stake") +
  theme_bw()+ 
  annotation_scale(location = "br", width_hint = 0.3,  
                   pad_x = unit(1, "cm"), pad_y = unit(0.5, "cm"))+
  annotation_north_arrow( location = "tl", pad_x = unit(0.2, "in"), pad_y = unit(0.1, "in"),
    style = north_arrow_fancy_orienteering)
cueva_plot

ggsave("prop_cueva.png",cueva_plot,width = 30,
       height = 30,units = "cm" ,dpi = 500, ) #png


```
